version: '3.8'

services:
  # Бэкенд
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - mongo

  # MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # Фронтенд
  frontend:
    build:
      context: ../warehouse-frontend  
      dockerfile: Dockerfile
    ports:
      - "80:80"  
    depends_on:
      - app 

volumes:
  mongo_data: